GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/621742495b8c60a78e20bb26

###
DELETE http://localhost:3001/api/persons/6218e9663ed200fbb1868b0c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"onlyOnePersonWithThisName",
    "number":"040-22334455"
}

###
PUT http://localhost:3001/api/persons/6218e77f3ed200fbb1868afa
Content-Type: application/json

{
    "name":"test",
    "number":"040-22334455"
}