DELETE http://localhost:3001/api/persons/621726dba6014c7de35293f7

###
GET http://localhost:3001/api/persons

###
PUT http://localhost:3001/api/persons/621726dba6014c7de35293f7
Content-Type: application/json

{
    "name":"superman",
    "number":"12"
}

###
POST https://pure-wildwood-94463.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"superman",
    "number":"34341231234"
}